# Generated by Django 5.2.14 on 2026-05-13 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("poblacion", models.IntegerField()),
                ("fecha_fundacion", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Planeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("distancia", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("P", "Pendiente"), ("C", "Completada")], max_length=1
                    ),
                ),
                (
                    "colonia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misiones",
                        to="colonias.colonia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misiones_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "mision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="colonias.mision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="colonia",
            name="planeta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colonias",
                to="colonias.planeta",
            ),
        ),
    ]
